server:
  port: 8080
mybatis:
  mapperLocations: classpath:mappers/*.xml
  settings:
       setting:
            lazyLoadingEnabled: true
            aggressiveLazyLoading: false
            cacheEnabled: true
logging:
  level:
    com.t3w.shiro.shirospring.mapper: debug
spring:
    application:
      name: shirotest
#    resources:
#        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
        username: root
        password: 3057
        maxActive: 10
        initialSize: 5
        minIdle: 5
t3w:
   datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: "jdbc:mysql://127.0.0.1:3306/zaokuang?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
       username: root
       password: 3057
       maxActive: 10
       initialSize: 5
       minIdle: 5
